#define BOOTMAGIC_ROW 2
#define BOOTMAGIC_COLUMN 0
#define BOOTMAGIC_ROW_RIGHT 2
#define BOOTMAGIC_COLUMN_RIGHT 5

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define MASTER_LEFT